# Generated by Django 5.0.2 on 2024-02-18 16:46

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, upload_to='books/%Y/%m/%d/', validators=[books.models.validate_svg]),
        ),
    ]
